# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import multimodal_inference_pb2 as multimodal__inference__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in multimodal_inference_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MultimodalInferenceStub(object):
    """统一多模态推理服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PredictEmotion = channel.unary_unary(
                '/multimodal_inference.MultimodalInference/PredictEmotion',
                request_serializer=multimodal__inference__pb2.EmotionRequest.SerializeToString,
                response_deserializer=multimodal__inference__pb2.EmotionResponse.FromString,
                _registered_method=True)
        self.PredictEmotionBatch = channel.unary_unary(
                '/multimodal_inference.MultimodalInference/PredictEmotionBatch',
                request_serializer=multimodal__inference__pb2.EmotionBatchRequest.SerializeToString,
                response_deserializer=multimodal__inference__pb2.EmotionBatchResponse.FromString,
                _registered_method=True)
        self.DetectSaliency = channel.unary_unary(
                '/multimodal_inference.MultimodalInference/DetectSaliency',
                request_serializer=multimodal__inference__pb2.SaliencyRequest.SerializeToString,
                response_deserializer=multimodal__inference__pb2.SaliencyResponse.FromString,
                _registered_method=True)
        self.GenerateVLM = channel.unary_stream(
                '/multimodal_inference.MultimodalInference/GenerateVLM',
                request_serializer=multimodal__inference__pb2.VLMRequest.SerializeToString,
                response_deserializer=multimodal__inference__pb2.VLMToken.FromString,
                _registered_method=True)
        self.GenerateVLMSync = channel.unary_unary(
                '/multimodal_inference.MultimodalInference/GenerateVLMSync',
                request_serializer=multimodal__inference__pb2.VLMRequest.SerializeToString,
                response_deserializer=multimodal__inference__pb2.VLMResponse.FromString,
                _registered_method=True)


class MultimodalInferenceServicer(object):
    """统一多模态推理服务
    """

    def PredictEmotion(self, request, context):
        """BERT 情绪分类（单条）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PredictEmotionBatch(self, request, context):
        """BERT 情绪分类（批量）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DetectSaliency(self, request, context):
        """ViT 显著度检测（视频流事件筛选）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateVLM(self, request, context):
        """VLM 推理（流式）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateVLMSync(self, request, context):
        """VLM 推理（同步）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MultimodalInferenceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PredictEmotion': grpc.unary_unary_rpc_method_handler(
                    servicer.PredictEmotion,
                    request_deserializer=multimodal__inference__pb2.EmotionRequest.FromString,
                    response_serializer=multimodal__inference__pb2.EmotionResponse.SerializeToString,
            ),
            'PredictEmotionBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.PredictEmotionBatch,
                    request_deserializer=multimodal__inference__pb2.EmotionBatchRequest.FromString,
                    response_serializer=multimodal__inference__pb2.EmotionBatchResponse.SerializeToString,
            ),
            'DetectSaliency': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectSaliency,
                    request_deserializer=multimodal__inference__pb2.SaliencyRequest.FromString,
                    response_serializer=multimodal__inference__pb2.SaliencyResponse.SerializeToString,
            ),
            'GenerateVLM': grpc.unary_stream_rpc_method_handler(
                    servicer.GenerateVLM,
                    request_deserializer=multimodal__inference__pb2.VLMRequest.FromString,
                    response_serializer=multimodal__inference__pb2.VLMToken.SerializeToString,
            ),
            'GenerateVLMSync': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateVLMSync,
                    request_deserializer=multimodal__inference__pb2.VLMRequest.FromString,
                    response_serializer=multimodal__inference__pb2.VLMResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'multimodal_inference.MultimodalInference', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('multimodal_inference.MultimodalInference', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MultimodalInference(object):
    """统一多模态推理服务
    """

    @staticmethod
    def PredictEmotion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/multimodal_inference.MultimodalInference/PredictEmotion',
            multimodal__inference__pb2.EmotionRequest.SerializeToString,
            multimodal__inference__pb2.EmotionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PredictEmotionBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/multimodal_inference.MultimodalInference/PredictEmotionBatch',
            multimodal__inference__pb2.EmotionBatchRequest.SerializeToString,
            multimodal__inference__pb2.EmotionBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DetectSaliency(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/multimodal_inference.MultimodalInference/DetectSaliency',
            multimodal__inference__pb2.SaliencyRequest.SerializeToString,
            multimodal__inference__pb2.SaliencyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateVLM(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/multimodal_inference.MultimodalInference/GenerateVLM',
            multimodal__inference__pb2.VLMRequest.SerializeToString,
            multimodal__inference__pb2.VLMToken.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateVLMSync(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/multimodal_inference.MultimodalInference/GenerateVLMSync',
            multimodal__inference__pb2.VLMRequest.SerializeToString,
            multimodal__inference__pb2.VLMResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
